[target.aarch64-unknown-linux-gnu]
linker = "gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-musleabihf-cross/bin/arm-linux-musleabihf-gcc"
